Merge up to r10596 from dahdi-linux/trunk (post-2.6.0).
This is WIP (the code compiles cleanly at this stage
but was not extensively tested).

diff --git a/build_tools/live_dahdi b/build_tools/live_dahdi
--- a/build_tools/live_dahdi
+++ b/build_tools/live_dahdi
@@ -4,6 +4,7 @@ LINUX_DIR=${LINUX_DIR:=.}
 TOOLS_DIR=${TOOLS_DIR:=../dahdi-tools}
 DYNAMIC_LOC="${DYNAMIC_LOC:-no}"
 DESTDIR=$PWD/live
+LIVE_DAHDI_RSYNC_DIR=${LIVE_DAHDI_RSYNC_DIR:-/tmp/dahdi}
 KVERS=${KVERS:-`uname -r`}
 XPP_SYNC=${XPP_SYNC:-auto}
 AST_SCRIPT=${AST_SCRIPT:-/etc/init.d/asterisk}
@@ -29,13 +30,16 @@ if [ ! -d "$LINUX_DIR" ]; then
 	exit 1
 fi
 
-if [ ! -d "$TOOLS_DIR" ]; then
-	echo >&2 "$0:dahdi-tools dir '$TOOLS_DIR' does not exits.  Aborting".
-	exit 1
-fi
 set -e
 LINUX_DIR_FULL=`(cd $LINUX_DIR; pwd)`
-TOOLS_DIR_FULL=`(cd $TOOLS_DIR; pwd)`
+
+set_tools_dir() {
+	if [ ! -d "$TOOLS_DIR" ]; then
+		echo >&2 "$0:dahdi-tools dir '$TOOLS_DIR' does not exits.  Aborting".
+		exit 1
+	fi
+	TOOLS_DIR_FULL=`(cd $TOOLS_DIR; pwd)`
+}
 
 # Give priority to our installed binaries:
 PATH=$DESTDIR/sbin:$DESTDIR/usr/sbin:$PATH
@@ -84,6 +88,9 @@ set_modules_to_load() {
 			MODULES_LOAD="$MODULES_LOAD xpp/xpd_fxo xpp/xpd_pri" 
 			if [ -r "$MODULES_DIR/xpp/xpd_bri.ko" ]; then
 				MODULES_LOAD="$MODULES_LOAD xpp/xpd_bri"
+			fi
+			if [ -r "$MODULES_DIR/xpp/xpd_echo.ko" ]; then
+				MODULES_LOAD="$MODULES_LOAD xpp/xpd_echo"
 			fi
 			MODULES_LOAD="$MODULES_LOAD xpp/xpp_usb"
 			;;
@@ -217,6 +224,7 @@ usage() {
 	echo "$me xpp-firm       (Reset and load xpp firmware)"
 	echo "$me genconf        dahdi_genconf; dahdi_cfg"
 	echo "$me asterisk       /etc/init.d/asterisk start"
+	echo "$me symlink_ast    symlink dahdi-channels.conf"
 	echo "$me rsync TARGET   (copy filea to /tmp/live in host TARGET)"
 	echo "$me exec  COMMAND  (Run COMMAND in 'live' environment)"
 	echo ""
@@ -227,15 +235,18 @@ usage() {
 case "$1" in
 configure)
 	shift
+	set_tools_dir
 	cd "$TOOLS_DIR"; ./configure --with-dahdi="$LINUX_DIR_FULL" "$@"
 	;;
 install)
 	shift
+	set_tools_dir
 	cd "$LINUX_DIR"; make install DESTDIR=$DESTDIR "$@"
 	cd "$TOOLS_DIR_FULL"; make install DESTDIR=$DESTDIR DYNFS=yes "$@"
 	;;
 config)
 	shift
+	set_tools_dir
 	cd "$TOOLS_DIR"; make config DESTDIR=$DESTDIR "$@"
 	mkdir -p $DESTDIR/etc/asterisk
 	cat >"$FIRMWARE_DIR/live-init.conf" <<EOF
@@ -244,6 +255,7 @@ export PATH
 dahdiconfdir="${DESTDIR}/etc/dahdi"
 export dahdiconfdir
 EOF
+	ln -s ../../../etc/dahdi/xpp.conf "$DESTDIR/usr/share/dahdi/"
 	;;
 rsync)
 	if [ $# -ne 2 ]; then
@@ -252,7 +264,7 @@ rsync)
 	fi
 	# copy the script itself and the installed directory to the
 	# target host:
-	rsync -ai "$0" $DESTDIR "$2:/tmp/"
+	rsync -ai "$0" $DESTDIR "$2:$LIVE_DAHDI_RSYNC_DIR"
 	;;
 unload)
 	# OK for Asterisk not to be running. TODO: a better test?
@@ -281,12 +293,19 @@ load)
 	# TODO: A local copy of Asterisk, configured with dahdi_gnconf. 
 	# doable, but trickier.
 	run_asterisk
+	if [ "$LIVE_DAHDI_FREEPBXDB" = 'yes' ]; then
+		GENCONF_PARAMETERS=$DESTDIR/etc/dahdi/genconf_parameters \
+			dahdi_genconf freepbxdb
+	fi
 	;;
 genconf)
 	genconf
 	;;
 asterisk)
 	run_asterisk
+	;;
+symlink_ast)
+	ln -sf "$DESTDIR/etc/asterisk/dahdi-channels.conf" /etc/asterisk/
 	;;
 reload)
 	$0 unload
@@ -311,6 +330,7 @@ xpp-firm)
 		"$FIRMWARE_DIR/xpp_fxloader" reset
 	sleep 5
 	XPP_FIRMWARE_DIR=$FIRMWARE_DIR \
+	XPP_CONFIG="$DESTDIR/etc/dahdi/xpp.conf" \
 		"$FIRMWARE_DIR/xpp_fxloader" load
 	;;
 help|'')
